[project]
name = "marker-nix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marker-pdf[full]>=1.10.1",
    "setuptools>=80.9.0",
    "streamlit>=1.50.0",
    "streamlit-ace>=0.1.1",
]
